code --install-extension 13xforever.language-x86-64-assembly
code --install-extension actboy168.lua-debug
code --install-extension arthurwang.vsc-prolog
code --install-extension bungcip.better-toml
code --install-extension DotJoshJohnson.xml
code --install-extension esbenp.prettier-vscode
code --install-extension ilmaria.generic-goto
code --install-extension Ionide.Ionide-fsharp
code --install-extension JakeBecker.elixir-ls
code --install-extension kalitaalexey.vscode-rust
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.powershell
code --install-extension rust-lang.rust
code --install-extension sjhuangx.vscode-scheme
code --install-extension tiehuis.zig
code --install-extension trixnz.vscode-lua
code --install-extension twxs.cmake
